import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import path from "path";
import fs from "node:fs/promises";

const isDev = process.argv[2] === "dev";

const banner = `
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const buildOptions = {
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  // Obsidian — Electron окружение с доступом к Node builtins, поэтому platform должен быть node.
  platform: "node",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: isDev ? "inline" : false,
  treeShaking: true,
  outfile: "dist/main.js",
  minify: !isDev,
  plugins: [
    {
      name: "alias-cross-fetch-to-obsidian-requestUrl",
      setup(build) {
        build.onResolve({ filter: /^cross-fetch$/ }, () => {
          return {
            path: path.resolve(process.cwd(), "src/caldav/crossFetchObsidian.ts"),
          };
        });
      },
    },
    {
      name: "copy-plugin-static",
      setup(build) {
        build.onEnd(async () => {
          await fs.mkdir("dist", { recursive: true });
          await fs.copyFile("resources/manifest.json", "dist/manifest.json");
          await fs.copyFile("resources/styles.css", "dist/styles.css");
          await fs.copyFile("resources/bridge-preload.cjs", "dist/bridge-preload.cjs");
        });
      },
    },
  ],
};

if (isDev) {
  const ctx = await esbuild.context(buildOptions);
  await ctx.watch();
  console.log("Watching for changes...");
} else {
  await esbuild.build(buildOptions);
}
